name: Docker Build CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER }}  
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD docker.io
      - name: Docker build Python
        run: |
          docker build ./FASTAPI -t image/python:1.0.0
      - name: Docker run container
        run: |
          docker run -d --name mycontainer -p 5003:5000 image/python:1.0.0

      
